//! Differential tests against Sphinx's own pattern matcher.
//!
//! The fixture is generated by tools/gen_pattern_fixture.py, which runs a
//! deterministic corpus through sphinx.util.matching.patmatch and records
//! every verdict. Regenerate with:
//!
//!     uv run --python 3.12 --with 'sphinx>=9.1,<9.2' python tools/gen_pattern_fixture.py

use sphinx_ultra::matching::pattern_match;

#[test]
fn matches_sphinx_util_matching() {
    let fixture_path = concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/tests/fixtures/pattern_differential.json"
    );
    let raw = std::fs::read_to_string(fixture_path).expect("read fixture");
    let fixture: serde_json::Value = serde_json::from_str(&raw).expect("parse fixture");
    let cases = fixture["cases"].as_array().expect("cases array");

    // Guard against a truncated or silently degenerated fixture
    assert!(
        cases.len() >= 500,
        "fixture holds only {} cases",
        cases.len()
    );

    let mut mismatches = Vec::new();
    for case in cases {
        let pattern = case["pattern"].as_str().expect("pattern");
        let path = case["path"].as_str().expect("path");
        let expected = case["match"].as_bool().expect("match");
        match pattern_match(path, pattern) {
            Ok(actual) if actual == expected => {}
            Ok(actual) => mismatches.push(format!(
                "pattern {pattern:?} vs path {path:?}: sphinx says {expected}, we say {actual}"
            )),
            Err(e) => mismatches.push(format!(
                "pattern {pattern:?} vs path {path:?}: sphinx says {expected}, we fail to compile: {e}"
            )),
        }
    }

    assert!(
        mismatches.is_empty(),
        "{} of {} cases diverge from sphinx.util.matching:\n{}",
        mismatches.len(),
        cases.len(),
        mismatches.join("\n")
    );
}
