name: 🐛 Bug Report
description: Create a report to help us improve Sphinx Ultra
title: "[Bug]: "
labels: ["bug", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! Please provide as much detail as possible.

  - type: textarea
    id: summary
    attributes:
      label: Bug Summary
      description: A clear and concise description of what the bug is.
      placeholder: Tell us what happened!
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: A clear and concise description of what actually happened.
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Please complete the following information
      value: |
        - OS: [e.g. Ubuntu 22.04, macOS 13.0, Windows 11]
        - Rust version: [e.g. 1.70.0]
        - Sphinx Ultra version: [e.g. 0.1.0]
        - Number of documentation files: [e.g. 1000]
    validations:
      required: true

  - type: textarea
    id: config
    attributes:
      label: Configuration
      description: Your sphinx-ultra.yaml configuration file (if relevant)
      render: yaml

  - type: textarea
    id: logs
    attributes:
      label: Log Output
      description: Any relevant log output (run with RUST_LOG=debug for verbose output)
      render: shell

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the problem here, including screenshots if applicable.
