blank_issues_enabled: false
contact_links:
  - name: 📚 Documentation
    url: https://github.com/salioglu/sphinx-ultra/blob/main/README.md
    about: Check our documentation for usage instructions and examples
  - name: 💬 Discussions
    url: https://github.com/salioglu/sphinx-ultra/discussions
    about: Ask questions and discuss ideas with the community
  - name: 🔒 Security Issues
    url: https://github.com/salioglu/sphinx-ultra/security/advisories/new
    about: Report security vulnerabilities privately
