#!/usr/bin/env python3
"""Generate src/transforms/smartquotes_tables.rs from docutils 0.22.4's smartquotes.

Regenerate with:

    PYTHONNOUSERSITE=1 uv run --python 3.12 --with docutils==0.22.4 \
        python tools/gen_smartquotes_tables.py
    cargo fmt --all

The `cargo fmt` is not optional: this script writes one array element per
line and rustfmt repacks them, so skipping it leaves a diff that is pure
formatting.

SphinxSmartQuotes (sphinx/transforms/__init__.py:361-415) runs docutils'
`educate_tokens`/`educateQuotes` (docutils/utils/smartquotes.py:565-735),
whose behaviour rests on data this script extracts mechanically rather than
by hand:

- `smartchars.quotes` (`:411-497`): every language tag's four quote
  strings (opening/closing primary, opening/closing secondary). A value is
  a 4-character string or, for the French variants, a 4-tuple of strings
  carrying a no-break space; both are emitted as four strings. Also the
  class-level `endash`/`emdash`/`ellipsis`/`apostrophe` and the ASCII
  fallback `smartchars.__init__` takes for a language it does not know.
- `RegularExpressions._CH_CLASSES` (`:510-515`): the `open`, `punct` and
  `dash` classes, as the exact sets of characters the compiled classes
  match (the `punct` class holds a literal space, and no `&`), and the
  `sep` class, asserted to be `\\s` plus ZWSP and ZWNJ.
- Python `re`'s `\\w` on a `str` pattern (`str.isalnum()` or `_`), as
  (first, last) code-point runs: the regexes' word class, which differs
  from Rust's `char::is_alphanumeric` (Other_Alphabetic, Nl, numerics).
  `\\s` and `\\d` are the crate's existing `py_isspace`/`py_decimal`
  (src/utils.rs); their member lists are emitted for a test cross-check.

The Python running this script is the one whose `re` semantics the tables
pin: run it under the 3.12 the oracle regeneration commands use.
"""

import re
import sys

import docutils
from docutils.utils import smartquotes

EXPECTED = "0.22.4"
assert docutils.__version__ == EXPECTED, (
    f"docutils {docutils.__version__} != {EXPECTED}; "
    "regenerate with the pinned command in the module docstring"
)

OUT = "src/transforms/smartquotes_tables.rs"
MAX = 0x110000


def rust_str(s: str) -> str:
    out = []
    for ch in s:
        cp = ord(ch)
        if ch == '"':
            out.append('\\"')
        elif ch == "\\":
            out.append("\\\\")
        elif 0x20 <= cp < 0x7F:
            out.append(ch)
        else:
            out.append("\\u{%x}" % cp)
    return '"' + "".join(out) + '"'


def rust_char(cp: int) -> str:
    ch = chr(cp)
    if ch == "'":
        return "'\\''"
    if ch == "\\":
        return "'\\\\'"
    if 0x20 <= cp < 0x7F:
        return "'" + ch + "'"
    return "'\\u{%x}'" % cp


def members(pattern: str) -> list:
    compiled = re.compile(pattern)
    verbose = re.compile(pattern, re.VERBOSE)
    found = [cp for cp in range(MAX) if compiled.fullmatch(chr(cp))]
    # The classes also appear inside re.VERBOSE patterns (OPENING_*): a
    # class keeps its whitespace there, so membership is the same.
    assert found == [cp for cp in range(MAX) if verbose.fullmatch(chr(cp))], pattern
    return found


def runs(code_points: list) -> list:
    out = []
    for cp in code_points:
        if out and out[-1][1] == cp - 1:
            out[-1][1] = cp
        else:
            out.append([cp, cp])
    return out


def main() -> int:
    chars = smartquotes.smartchars
    quotes = {}
    for tag, value in chars.quotes.items():
        assert tag == tag.lower(), f"quote key {tag!r} is not lowercase"
        parts = tuple(value)
        assert len(parts) == 4, f"{tag!r}: {value!r}"
        quotes[tag] = parts
    ascii_quotes = tuple('""\'\'')
    fallback = chars("no-such-language")
    assert (fallback.opquote, fallback.cpquote, fallback.osquote, fallback.csquote) == ascii_quotes

    classes = smartquotes.RegularExpressions._CH_CLASSES
    open_ = members(classes["open"])
    punct = members(classes["punct"])
    dash = members(classes["dash"])
    sep = members(classes["sep"])
    space = members(r"\s")
    digit = members(r"\d")
    word = [cp for cp in range(MAX) if re.match(r"\w", chr(cp))]
    assert word == [cp for cp in range(MAX) if chr(cp).isalnum() or chr(cp) == "_"]
    assert sep == sorted(space + [0x200B, 0x200C]), "sep is no longer \\s + ZWSP + ZWNJ"
    max_hyphens = max(tag.count("-") for tag in quotes)

    lines = [
        "//! GENERATED by tools/gen_smartquotes_tables.py from docutils %s's"
        % docutils.__version__,
        "//! `docutils/utils/smartquotes.py` under Python %s (regen:"
        % sys.version.split()[0],
        "//! `PYTHONNOUSERSITE=1 uv run --python 3.12 --with docutils==0.22.4 \\",
        "//!     python tools/gen_smartquotes_tables.py`, then `cargo fmt --all`).",
        "//! Do not edit by hand.",
        "",
        "/// `smartchars.quotes` (`smartquotes.py:411-497`), sorted by tag: each",
        "/// language tag's opening primary, closing primary, opening secondary",
        "/// and closing secondary quote.",
        "pub(crate) const QUOTES: &[(&str, [&str; 4])] = &[",
    ]
    for tag in sorted(quotes):
        parts = ", ".join(rust_str(p) for p in quotes[tag])
        lines.append(f"    ({rust_str(tag)}, [{parts}]),")
    lines += [
        "];",
        "",
        "/// The quotes `smartchars(language)` falls back to for a language",
        "/// [`QUOTES`] does not have (`smartquotes.py:499-505`): plain ASCII.",
        "pub(crate) const ASCII_QUOTES: [&str; 4] = [%s];"
        % ", ".join(rust_str(q) for q in ascii_quotes),
        "",
        "/// The most `-` any [`QUOTES`] tag holds: a combination of more subtags",
        "/// than this can never name one.",
        f"pub(crate) const MAX_TAG_HYPHENS: usize = {max_hyphens};",
        "",
        "/// `smartchars.endash` (`smartquotes.py:390`).",
        f"pub(crate) const ENDASH: &str = {rust_str(chars.endash)};",
        "/// `smartchars.emdash` (`smartquotes.py:391`).",
        f"pub(crate) const EMDASH: &str = {rust_str(chars.emdash)};",
        "/// `smartchars.ellipsis` (`smartquotes.py:392`).",
        f"pub(crate) const ELLIPSIS: &str = {rust_str(chars.ellipsis)};",
        "/// `smartchars.apostrophe` (`smartquotes.py:393`).",
        f"pub(crate) const APOSTROPHE: &str = {rust_str(chars.apostrophe)};",
        "",
        "/// `_CH_CLASSES['open']` (`smartquotes.py:510`): the opening braces.",
        "pub(crate) const OPEN: &[char] = &[%s];" % ", ".join(rust_char(c) for c in open_),
        "",
        "/// `_CH_CLASSES['punct']` (`smartquotes.py:512`), sorted: ASCII",
        "/// punctuation and the space, but no `&`.",
        "pub(crate) const PUNCT: &[char] = &[",
    ]
    lines += [f"    {rust_char(c)}," for c in punct]
    lines += [
        "];",
        "",
        "/// `_CH_CLASSES['dash']` (`smartquotes.py:513`).",
        "pub(crate) const DASH: &[char] = &[%s];" % ", ".join(rust_char(c) for c in dash),
        "",
        "/// `_CH_CLASSES['sep']` (`smartquotes.py:514`) beyond `\\s`: ZWSP and",
        "/// ZWNJ.",
        "pub(crate) const SEP_EXTRA: &[char] = &[%s];"
        % ", ".join(rust_char(c) for c in sorted(set(sep) - set(space))),
        "",
        "/// Python `re`'s `\\w` on a `str` pattern — `str.isalnum()` or `_` —",
        "/// as sorted, disjoint (first, last) code-point runs.",
        "pub(crate) const WORD_RUNS: &[(u32, u32)] = &[",
    ]
    lines += ["    (0x%X, 0x%X)," % (a, b) for a, b in runs(word)]
    lines += [
        "];",
        "",
        "/// Every code point Python `re`'s `\\s` matches on a `str` pattern —",
        "/// what `crate::utils::py_isspace` is checked against.",
        "#[cfg(test)]",
        "pub(crate) const SPACE: &[u32] = &[%s];" % ", ".join("0x%X" % c for c in space),
        "",
        "/// How many code points Python `re`'s `\\d` matches on a `str` pattern",
        "/// — what `crate::utils::py_decimal` is checked against.",
        "#[cfg(test)]",
        f"pub(crate) const DIGIT_COUNT: usize = {len(digit)};",
        "",
    ]
    with open(OUT, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))
    print(
        f"wrote {OUT}: {len(quotes)} quote sets, {len(punct)} punct, "
        f"{len(runs(word))} word runs, {len(space)} spaces, {len(digit)} digits"
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
