#!/usr/bin/env python3
"""Generate src/rst/punctuation.rs from docutils 0.22.4 punctuation_chars.

Regenerate with:

    uv run --python 3.12 --with docutils==0.22.4 python tools/gen_punctuation_tables.py

The Inliner's start-string prefix, end-string suffix, and quoted_start
pairing all depend on these exact character sets; hand-transcribing them
would risk byte-parity drift, so they are extracted mechanically.
Two distinct membership semantics exist upstream (probe-verified):
- REGEX classes (start/end patterns): the raw strings contain regex escapes
  (backslash+char), so we emit the UNESCAPED character sets for class
  membership tests in Rust.
- STRING pairing (quoted_start's match_chars): openers/closers indexed as
  plain strings INCLUDING the literal backslashes that are regex escapes
  upstream — we emit those verbatim too (openers_raw/closers_raw).
"""

import re
import sys

import docutils
from docutils.utils import punctuation_chars

EXPECTED = "0.22.4"


def unescape_class(s: str) -> str:
    """Resolve regex escapes (backslash+char -> char) in a class string."""
    return re.sub(r"\\(.)", r"\1", s)


def rust_char_array(name: str, chars: str) -> str:
    items = ", ".join(f"'\\u{{{ord(c):x}}}'" for c in sorted(set(chars)))
    return f"pub const {name}: &[char] = &[{items}];\n"


def main() -> int:
    assert docutils.__version__ == EXPECTED, docutils.__version__
    openers = unescape_class(punctuation_chars.openers)
    closers = unescape_class(punctuation_chars.closers)
    delimiters = unescape_class(punctuation_chars.delimiters)
    closing_delimiters = unescape_class(punctuation_chars.closing_delimiters)
    quote_pairs = punctuation_chars.quote_pairs

    out = []
    out.append("//! GENERATED by tools/gen_punctuation_tables.py from docutils 0.22.4\n")
    out.append("//! `docutils.utils.punctuation_chars` - do not edit by hand.\n")
    out.append("//! Regenerate: uv run --python 3.12 --with docutils==0.22.4 \\\n")
    out.append("//!     python tools/gen_punctuation_tables.py\n\n")
    out.append("/// Regex-class members of the start-string prefix (unescaped).\n")
    out.append(rust_char_array("OPENERS", openers))
    out.append("\n/// Regex-class members used by quoted_start pairing (unescaped).\n")
    out.append(rust_char_array("CLOSERS", closers))
    out.append("\n/// Delimiters valid before a start-string and after an end-string.\n")
    out.append(rust_char_array("DELIMITERS", delimiters))
    out.append("\n/// Extra chars valid after an end-string (sentence punctuation).\n")
    out.append(rust_char_array("CLOSING_DELIMITERS", closing_delimiters))
    def ordered_char_array(name: str, chars: str) -> str:
        # ORDER-PRESERVING, duplicates kept: index pairing depends on it.
        items = ", ".join(f"'\\u{{{ord(c):x}}}'" for c in chars)
        return f"pub const {name}: &[char] = &[{items}];\n"

    def rust_str(s: str) -> str:
        return '"' + "".join(f"\\u{{{ord(c):x}}}" for c in s) + '"'

    out.append("\n/// quoted_start pairing: openers/closers with upstream ORDER and the\n")
    out.append("/// regex-escape backslashes still present (index-paired, like the\n")
    out.append("/// Python strings docutils indexes into).\n")
    out.append(ordered_char_array("OPENERS_RAW", punctuation_chars.openers))
    out.append(ordered_char_array("CLOSERS_RAW", punctuation_chars.closers))
    out.append("\n/// Extra quote pairings beyond positional opener->closer matching.\n")
    out.append("pub const QUOTE_PAIRS: &[(char, &str)] = &[\n")
    for k in sorted(quote_pairs):
        out.append(f"    ('\\u{{{ord(k):x}}}', {rust_str(quote_pairs[k])}),\n")
    out.append("];\n")

    text = "".join(out)
    with open("src/rst/punctuation.rs", "w", encoding="utf-8") as f:
        f.write(text)
    print(
        f"wrote src/rst/punctuation.rs: {len(openers)} openers, {len(closers)} closers, "
        f"{len(delimiters)} delimiters, {len(quote_pairs)} quote pairs"
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
