#!/usr/bin/env python3
"""Generate src/rst/digits.rs from Python's own unicodedata.

Regenerate with:

    uv run --python 3.12 python tools/gen_digit_tables.py

Encodes the three char classes Python's int()/str.isdigit() distinguish:
- DECIMAL ranges (category Nd, unicodedata.decimal defined): int() accepts
  these, value = codepoint - range start.
- NON-DECIMAL digit chars (unicodedata.digit defined but decimal not, e.g.
  '²'): str.isdigit() is True but int() raises.
The parser's option converters must match int() exactly (docutils feeds
option values straight into int()).
"""

import sys
import unicodedata

decimals = []
nondecimal = []
for cp in range(0x110000):
    c = chr(cp)
    try:
        d = unicodedata.decimal(c)
    except (TypeError, ValueError):
        d = None
    if d is not None:
        decimals.append((cp, d))
        continue
    try:
        unicodedata.digit(c)
    except (TypeError, ValueError):
        continue
    nondecimal.append(cp)

# Compress decimals into (start_of_zero, end) runs where value = cp - start.
runs = []
for cp, d in decimals:
    zero = cp - d
    if runs and runs[-1][0] == zero and cp == runs[-1][1] + 1:
        runs[-1] = (zero, cp)
    elif runs and runs[-1][0] == zero:
        # non-contiguous same-zero (does not occur, but be safe)
        runs.append((zero, cp))
    elif not runs or runs[-1][0] != zero:
        runs.append((zero, cp))

out = open("src/rst/digits.rs", "w")
out.write(
    "//! GENERATED by tools/gen_digit_tables.py from Python %s unicodedata\n"
    "//! (regen: `uv run --python 3.12 python tools/gen_digit_tables.py`).\n"
    "//! Do not edit by hand.\n\n" % sys.version.split()[0]
)
out.write("/// (zero_codepoint, last_codepoint) runs of DECIMAL digits\n")
out.write("/// (Python `unicodedata.decimal` defined; `int()` accepts).\n")
out.write("pub(crate) const DECIMAL_RUNS: &[(u32, u32)] = &[\n")
for zero, end in runs:
    out.write("    (0x%X, 0x%X),\n" % (zero, end))
out.write("];\n\n")
out.write("/// Chars where Python str.isdigit() is true but int() RAISES\n")
out.write("/// (digit property without decimal property, e.g. superscripts).\n")
out.write("pub(crate) const NON_DECIMAL_DIGITS: &[u32] = &[\n")
for i in range(0, len(nondecimal), 8):
    out.write("    " + ", ".join("0x%X" % c for c in nondecimal[i : i + 8]) + ",\n")
out.write("];\n\n")
out.write(
    """/// Python int()-compatible decimal value of a char.
pub(crate) fn decimal_digit_value(c: char) -> Option<u32> {
    let cp = c as u32;
    DECIMAL_RUNS
        .iter()
        .find(|(zero, end)| cp >= *zero && cp <= *end)
        .map(|(zero, _)| cp - zero)
}

/// Python str.isdigit() for one char.
pub(crate) fn is_python_digit(c: char) -> bool {
    decimal_digit_value(c).is_some() || NON_DECIMAL_DIGITS.binary_search(&(c as u32)).is_ok()
}
"""
)
out.close()
print("wrote src/rst/digits.rs: %d decimal runs, %d non-decimal digits" % (len(runs), len(nondecimal)))
